# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes atlas numpy scipy nose scikit-learn
  - wget http://stat.rutgers.edu/home/tzhang/software/rgf/rgf1.2.zip
  - unzip rgf1.2.zip
  - cd rgf1.2
  - make
  - cd ..
  - sed '10a loc_exec = "rgf1.2/bin/rgf.exe"' rgf/rgf.py
script:
  - python rgf/test.py
